# Generated by Django 2.2.2 on 2019-06-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('checkout', '0002_ordemitem_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdemItem',
            new_name='OrderItem',
        ),
    ]
