# Generated by Django 2.2.2 on 2019-06-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20190613_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('deposit', 'Depósito'), ('pagseguro', 'PagSeguro'), ('paypal', 'PayPal')], default='deposit', max_length=20, verbose_name='Opção de pagamento'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete='SET_NULL', related_name='items', to='checkout.Order', verbose_name='Pedido'),
        ),
    ]
